In [2]:
## 필요한 라이브러리 임포트
import pandas as pd

In [6]:
import os

print(os.getcwd())

/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/code

In [17]:
# file=pd.read_csv('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/tourPension.csv', encoding = 'cp949')

In [13]:
with open('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/tour_pension.csv', 'r', encoding='cp949', errors='replace') as file:
    data = file.read()

In [21]:
file=pd.read_csv('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/tourPension.csv', encoding = 'euc-kr')

In [22]:
file

,번호,개방서비스명,개방서비스아이디,개방자치단체코드,관리번호,인허가일자,인허가취소일자,영업상태구분코드,영업상태명,상세영업상태코드,...,의무실유무,안내소유무,기획여행보험시작일자,기획여행보험종료일자,자본금,보험시작일자,보험종료일자,부대시설내역,시설규모,Unnamed: 63
0,1,관광펜션업,03_11_02_P,4341000,CDFI3261092005000001,2005-08-29,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.0,NaN
1,2,관광펜션업,03_11_02_P,4341000,CDFI3261092007000001,2007-01-09,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,5.000000e+07,NaN,NaN,NaN,0.0,NaN
2,3,관광펜션업,03_11_02_P,4341000,CDFI3261092008000001,2008-11-19,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,721.0,NaN
3,4,관광펜션업,03_11_02_P,4341000,CDFI3261092015000001,2015-02-11,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,0.0,NaN
4,5,관광펜션업,03_11_02_P,4400000,CDFI3261092009000006,2009-07-07,NaN,2,휴업,2,...,NaN,NaN,NaN,NaN,3.500000e+07,NaN,NaN,NaN,147.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,1062,관광펜션업,03_11_02_P,4480000,CDFI3261092003000001,2003-11-13,2015-03-30,4,취소/말소/만료/정지/중지,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167.0,NaN
1062,1063,관광펜션업,03_11_02_P,4480000,CDFI3261092003000003,2003-12-03,2015-01-19,4,취소/말소/만료/정지/중지,33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,177.0,NaN
1063,1064,관광펜션업,03_11_02_P,4620000,CDFI3261092010000004,2010-08-03,NaN,4,취소/말소/만료/정지/중지,35,...,NaN,NaN,NaN,NaN,1.200000e+09,NaN,NaN,NaN,885.0,NaN
1064,1065,관광펜션업,03_11_02_P,4620000,CDFI3261092007000002,2007-10-11,NaN,4,취소/말소/만료/정지/중지,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1283.0,NaN
1065,1066,관광펜션업,03_11_02_P,5670000,CDFI3261092018000001,2018-01-09,NaN,4,취소/말소/만료/정지/중지,35,...,NaN,NaN,NaN,NaN,3.000000e+08,NaN,NaN,NaN,892.0,NaN

In [23]:
file = file.drop(['개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자', '영업상태구분코드', '의무실유무', '안내소유무', '상세영업상태코드'], axis=1)
print(file)

        번호 개방서비스명           영업상태명 상세영업상태명        폐업일자      휴업시작일자      휴업종료일자  \
0        1  관광펜션업              휴업      휴업         NaN  2019-04-04  2021-12-31
1        2  관광펜션업              휴업      휴업         NaN  2019-04-04  2021-12-31
2        3  관광펜션업              휴업      휴업         NaN         NaN         NaN
3        4  관광펜션업              휴업      휴업         NaN  2015-11-11  2016-11-09
4        5  관광펜션업              휴업      휴업         NaN  2013-10-14  2014-10-14
...    ...    ...             ...     ...         ...         ...         ...
1061  1062  관광펜션업  취소/말소/만료/정지/중지    지정취소         NaN         NaN         NaN
1062  1063  관광펜션업  취소/말소/만료/정지/중지    지정취소         NaN         NaN         NaN
1063  1064  관광펜션업  취소/말소/만료/정지/중지    직권말소  2015-11-03         NaN         NaN
1064  1065  관광펜션업  취소/말소/만료/정지/중지    직권말소         NaN         NaN         NaN
1065  1066  관광펜션업  취소/말소/만료/정지/중지    직권말소  2021-12-24         NaN         NaN

      재개업일자          소재지전화  소재지면적  ... 방송시설유무 발전시설유무 기획여행보험시작일자 기획여행보험종료일자  \
0       NaN            NaN    NaN  ...    NaN    NaN        NaN        NaN
1       NaN   033-636-4773    NaN  ...    NaN    NaN        NaN        NaN
2       NaN   033-632-6363    NaN  ...    NaN    NaN        NaN        NaN
3       NaN   033-632-5156    NaN  ...    NaN    NaN        NaN        NaN
4       NaN            NaN    NaN  ...    NaN    NaN        NaN        NaN
...     ...            ...    ...  ...    ...    ...        ...        ...
1061    NaN   043)421-5206    NaN  ...    NaN    NaN        NaN        NaN
1062    NaN  (043)422-6221    NaN  ...    NaN    NaN        NaN        NaN
1063    NaN   041-672-0973    NaN  ...    NaN    NaN        NaN        NaN
1064    NaN   041-672-8080    NaN  ...    NaN    NaN        NaN        NaN
1065    NaN            NaN    NaN  ...    NaN    NaN        NaN        NaN

               자본금 보험시작일자 보험종료일자 부대시설내역    시설규모  Unnamed: 63
0     0.000000e+00    NaN    NaN    NaN     0.0          NaN
1     5.000000e+07    NaN    NaN    NaN     0.0          NaN
2     0.000000e+00    NaN    NaN    NaN   721.0          NaN
3     0.000000e+00    NaN    NaN    NaN     0.0          NaN
4     3.500000e+07    NaN    NaN    NaN   147.0          NaN
...            ...    ...    ...    ...     ...          ...
1061           NaN    NaN    NaN    NaN   167.0          NaN
1062           NaN    NaN    NaN    NaN   177.0          NaN
1063  1.200000e+09    NaN    NaN    NaN   885.0          NaN
1064           NaN    NaN    NaN    NaN  1283.0          NaN
1065  3.000000e+08    NaN    NaN    NaN   892.0          NaN

[1066 rows x 55 columns]

In [25]:
file.columns

Index(['번호', '개방서비스명', '영업상태명', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자',
       '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호', '사업장명',
       '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(x)', '좌표정보(y)',
       '문화체육업종명', '문화사업자구분명', '지역구분명', '총층수', '주변환경명', '제작취급품목내용', '보험기관명',
       '건물용도명', '지상층수', '지하층수', '객실수', '건축연면적', '영문상호명', '영문상호주소', '선박총톤수',
       '선박척수', '선박제원', '무대면적', '좌석수', '기념품종류', '회의실별동시수용인원', '시설면적', '놀이기구수내역',
       '놀이시설수', '방송시설유무', '발전시설유무', '기획여행보험시작일자', '기획여행보험종료일자', '자본금',
       '보험시작일자', '보험종료일자', '부대시설내역', '시설규모', 'Unnamed: 63'],
      dtype='object')

In [26]:
file = file.drop(['상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자', '재개업일자',
       '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명우편번호', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '문화체육업종명', '문화사업자구분명', '지역구분명', '총층수', '주변환경명', '제작취급품목내용', '보험기관명',
       '건물용도명', '지상층수', '지하층수', '객실수', '건축연면적', '영문상호명', '영문상호주소', '선박총톤수',
       '선박척수', '선박제원', '무대면적', '좌석수', '기념품종류', '회의실별동시수용인원', '시설면적', '놀이기구수내역',
       '놀이시설수', '방송시설유무', '발전시설유무', '기획여행보험시작일자', '기획여행보험종료일자', '자본금',
       '보험시작일자', '보험종료일자', '부대시설내역', '시설규모', 'Unnamed: 63'], axis=1)
print(file)

        번호 개방서비스명           영업상태명                                 도로명전체주소  \
0        1  관광펜션업              휴업               강원특별자치도 고성군 토성면 잼버리동로 511
1        2  관광펜션업              휴업               강원특별자치도 고성군 토성면 잼버리동로 511
2        3  관광펜션업              휴업                 강원특별자치도 고성군 토성면 풍곡1길 31
3        4  관광펜션업              휴업                강원특별자치도 고성군 죽왕면 백도해변길 78
4        5  관광펜션업              휴업               충청북도 제천시 청풍면 청풍호로44길 29-1
...    ...    ...             ...                                     ...
1061  1062  관광펜션업  취소/말소/만료/정지/중지                    충청북도 단양군 가곡면 가대2길 10
1062  1063  관광펜션업  취소/말소/만료/정지/중지                    충청북도 단양군 가곡면 가대1길 55
1063  1064  관광펜션업  취소/말소/만료/정지/중지                     충청남도 태안군 남면 청포대길 84
1064  1065  관광펜션업  취소/말소/만료/정지/중지                 충청남도 태안군 고남면 가경주길 47-71
1065  1066  관광펜션업  취소/말소/만료/정지/중지  경상남도 창원시 마산합포구 진전면 회진로 742-45, 히든비치리조트

               사업장명        좌표정보(x)        좌표정보(y)
0            주성관광펜션  336820.049139  527182.508125
1          제이에스관광펜션  336847.223237  527293.573937
2            파인로그펜션  334426.047240  526627.868791
3            밴쿠버콘도텔  335102.636155  534339.746669
4     플로리안관광펜션(김 면)  304245.829329  391415.466727
...             ...            ...            ...
1061         한울관광펜션  325233.751120  394366.316117
1062   추억을선물하는집관광펜션  325305.167214  394408.459409
1063           파티파티  137548.894217  349159.989879
1064       아틀랜틱 리조트  147311.686902  323314.306869
1065   히든비치리조트 관광펜션  329841.051107  174071.910868

[1066 rows x 7 columns]

In [27]:
file.columns

Index(['번호', '개방서비스명', '영업상태명', '도로명전체주소', '사업장명', '좌표정보(x)', '좌표정보(y)'], dtype='object')

In [28]:
file.columns = ['number', 'service', 'condition', 'address', 'pension_name', 'latitude', 'longitude']

In [29]:
file.columns

Index(['number', 'service', 'condition', 'address', 'pension_name', 'latitude',
       'longitude'],
      dtype='object')

In [30]:
file

,number,service,condition,address,pension_name,latitude,longitude
0,1,관광펜션업,휴업,강원특별자치도 고성군 토성면 잼버리동로 511,주성관광펜션,336820.049139,527182.508125
1,2,관광펜션업,휴업,강원특별자치도 고성군 토성면 잼버리동로 511,제이에스관광펜션,336847.223237,527293.573937
2,3,관광펜션업,휴업,강원특별자치도 고성군 토성면 풍곡1길 31,파인로그펜션,334426.047240,526627.868791
3,4,관광펜션업,휴업,강원특별자치도 고성군 죽왕면 백도해변길 78,밴쿠버콘도텔,335102.636155,534339.746669
4,5,관광펜션업,휴업,충청북도 제천시 청풍면 청풍호로44길 29-1,플로리안관광펜션(김 면),304245.829329,391415.466727
...,...,...,...,...,...,...,...
1061,1062,관광펜션업,취소/말소/만료/정지/중지,충청북도 단양군 가곡면 가대2길 10,한울관광펜션,325233.751120,394366.316117
1062,1063,관광펜션업,취소/말소/만료/정지/중지,충청북도 단양군 가곡면 가대1길 55,추억을선물하는집관광펜션,325305.167214,394408.459409
1063,1064,관광펜션업,취소/말소/만료/정지/중지,충청남도 태안군 남면 청포대길 84,파티파티,137548.894217,349159.989879
1064,1065,관광펜션업,취소/말소/만료/정지/중지,충청남도 태안군 고남면 가경주길 47-71,아틀랜틱 리조트,147311.686902,323314.306869
1065,1066,관광펜션업,취소/말소/만료/정지/중지,"경상남도 창원시 마산합포구 진전면 회진로 742-45, 히든비치리조트",히든비치리조트 관광펜션,329841.051107,174071.910868

In [31]:
file_drop = file[file['condition'].str.contains('취소')].index
file = file.drop(file_drop)

In [32]:
file

,number,service,condition,address,pension_name,latitude,longitude
0,1,관광펜션업,휴업,강원특별자치도 고성군 토성면 잼버리동로 511,주성관광펜션,336820.049139,527182.508125
1,2,관광펜션업,휴업,강원특별자치도 고성군 토성면 잼버리동로 511,제이에스관광펜션,336847.223237,527293.573937
2,3,관광펜션업,휴업,강원특별자치도 고성군 토성면 풍곡1길 31,파인로그펜션,334426.047240,526627.868791
3,4,관광펜션업,휴업,강원특별자치도 고성군 죽왕면 백도해변길 78,밴쿠버콘도텔,335102.636155,534339.746669
4,5,관광펜션업,휴업,충청북도 제천시 청풍면 청풍호로44길 29-1,플로리안관광펜션(김 면),304245.829329,391415.466727
...,...,...,...,...,...,...,...
1015,1016,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 한과마을길 560,파인힐,358407.042527,480133.319231
1016,1017,관광펜션업,영업/정상,경상북도 경주시 강동면 호명큰골길 61,스테이숲숲,403201.463637,276610.297702
1017,1018,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 순포안길 47-14,강릉스테이이플,365605.775424,481323.924803
1018,1019,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-78,가둘기정원 꽃넘이,245371.103278,488732.779980
1019,1020,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-80,보쏭,245372.171849,488758.951335

In [33]:
file_drop = file[file['condition'].str.contains('휴업')].index
file = file.drop(file_drop)

In [34]:
file

,number,service,condition,address,pension_name,latitude,longitude
5,6,관광펜션업,폐업,경상북도 경주시 하동1길 45-7 (하동),메리골드 펜션,408712.264714,257334.489940
6,7,관광펜션업,폐업,경상북도 경주시 시동로 86-57 (시래동),아띠 펜션,406748.435237,255098.479661
7,8,관광펜션업,폐업,경상북도 경주시 보불로 126-55 (하동),비버리 펜션,409426.234255,257513.538255
8,9,관광펜션업,폐업,경상북도 경주시 보불로 126-57 (하동),비버리 힐,409411.494187,257512.464964
9,10,관광펜션업,폐업,충청남도 보령시 고잠2길 16-18 (신흑동),대천바다여행펜션,156522.261889,312458.679295
...,...,...,...,...,...,...,...
1015,1016,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 한과마을길 560,파인힐,358407.042527,480133.319231
1016,1017,관광펜션업,영업/정상,경상북도 경주시 강동면 호명큰골길 61,스테이숲숲,403201.463637,276610.297702
1017,1018,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 순포안길 47-14,강릉스테이이플,365605.775424,481323.924803
1018,1019,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-78,가둘기정원 꽃넘이,245371.103278,488732.779980
1019,1020,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-80,보쏭,245372.171849,488758.951335

In [35]:
file_drop = file[file['condition'].str.contains('폐업')].index
file = file.drop(file_drop)

In [36]:
file

,number,service,condition,address,pension_name,latitude,longitude
254,255,관광펜션업,영업/정상,경상북도 문경시 마성면 구랑로 333,강이 있는 풍경,300112.510243,351902.958443
255,256,관광펜션업,영업/정상,경상북도 문경시 문경읍 주흘로 241-14,리앙스,300988.024332,360123.323904
256,257,관광펜션업,영업/정상,경상북도 문경시 문경읍 새재1길 47,문경새재국민여가캠핑장,295962.786318,362023.271676
257,258,관광펜션업,영업/정상,경상북도 경주시 보불로 66-29 (마동),서라벌 토기 관광펜션,409295.124711,257046.138521
258,259,관광펜션업,영업/정상,경상북도 문경시 문경읍 활공장길 115,이둔펜션,303289.910675,360275.224933
...,...,...,...,...,...,...,...
1015,1016,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 한과마을길 560,파인힐,358407.042527,480133.319231
1016,1017,관광펜션업,영업/정상,경상북도 경주시 강동면 호명큰골길 61,스테이숲숲,403201.463637,276610.297702
1017,1018,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 순포안길 47-14,강릉스테이이플,365605.775424,481323.924803
1018,1019,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-78,가둘기정원 꽃넘이,245371.103278,488732.779980
1019,1020,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-80,보쏭,245372.171849,488758.951335

In [37]:
import numpy as np

file.dropna(axis=0)

,number,service,condition,address,pension_name,latitude,longitude
254,255,관광펜션업,영업/정상,경상북도 문경시 마성면 구랑로 333,강이 있는 풍경,300112.510243,351902.958443
255,256,관광펜션업,영업/정상,경상북도 문경시 문경읍 주흘로 241-14,리앙스,300988.024332,360123.323904
256,257,관광펜션업,영업/정상,경상북도 문경시 문경읍 새재1길 47,문경새재국민여가캠핑장,295962.786318,362023.271676
257,258,관광펜션업,영업/정상,경상북도 경주시 보불로 66-29 (마동),서라벌 토기 관광펜션,409295.124711,257046.138521
258,259,관광펜션업,영업/정상,경상북도 문경시 문경읍 활공장길 115,이둔펜션,303289.910675,360275.224933
...,...,...,...,...,...,...,...
1015,1016,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 한과마을길 560,파인힐,358407.042527,480133.319231
1016,1017,관광펜션업,영업/정상,경상북도 경주시 강동면 호명큰골길 61,스테이숲숲,403201.463637,276610.297702
1017,1018,관광펜션업,영업/정상,강원특별자치도 강릉시 사천면 순포안길 47-14,강릉스테이이플,365605.775424,481323.924803
1018,1019,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-78,가둘기정원 꽃넘이,245371.103278,488732.779980
1019,1020,관광펜션업,영업/정상,경기도 가평군 북면 꽃넘이길 115-80,보쏭,245372.171849,488758.951335

In [39]:
file.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       number  service  condition  address  pension_name  latitude  longitude
254    False    False      False    False         False     False      False
255    False    False      False    False         False     False      False
256    False    False      False    False         False     False      False
257    False    False      False    False         False     False      False
258    False    False      False    False         False     False      False
...      ...      ...        ...      ...           ...       ...        ...
1015   False    False      False    False         False     False      False
1016   False    False      False    False         False     False      False
1017   False    False      False    False         False     False      False
1018   False    False      False    False         False     False      False
1019   False    False      False    False         False     False      False

[766 rows x 7 columns]>

In [42]:
#한 값이라도 결측치가 있다면 제거
print(file.dropna(how='any'))

      number service condition                     address pension_name  \
254      255   관광펜션업     영업/정상        경상북도 문경시 마성면 구랑로 333     강이 있는 풍경
255      256   관광펜션업     영업/정상     경상북도 문경시 문경읍 주흘로 241-14          리앙스
256      257   관광펜션업     영업/정상        경상북도 문경시 문경읍 새재1길 47  문경새재국민여가캠핑장
257      258   관광펜션업     영업/정상     경상북도 경주시 보불로 66-29 (마동)  서라벌 토기 관광펜션
258      259   관광펜션업     영업/정상       경상북도 문경시 문경읍 활공장길 115         이둔펜션
...      ...     ...       ...                         ...          ...
1015    1016   관광펜션업     영업/정상   강원특별자치도 강릉시 사천면 한과마을길 560          파인힐
1016    1017   관광펜션업     영업/정상       경상북도 경주시 강동면 호명큰골길 61        스테이숲숲
1017    1018   관광펜션업     영업/정상  강원특별자치도 강릉시 사천면 순포안길 47-14      강릉스테이이플
1018    1019   관광펜션업     영업/정상      경기도 가평군 북면 꽃넘이길 115-78    가둘기정원 꽃넘이
1019    1020   관광펜션업     영업/정상      경기도 가평군 북면 꽃넘이길 115-80           보쏭

           latitude      longitude
254   300112.510243  351902.958443
255   300988.024332  360123.323904
256   295962.786318  362023.271676
257   409295.124711  257046.138521
258   303289.910675  360275.224933
...             ...            ...
1015  358407.042527  480133.319231
1016  403201.463637  276610.297702
1017  365605.775424  481323.924803
1018  245371.103278  488732.779980
1019  245372.171849  488758.951335

[745 rows x 7 columns]

In [43]:
file.isnull().sum()

number          0
service         0
condition       0
address         0
pension_name    0
latitude        0
longitude       0
dtype: int64

In [44]:
#DataFrame CSV 파일로 저장
file.to_csv('tourPension_file.csv', encoding='utf-8-sig')

In [45]:
## 여기서부터는 로컬 워케이션 시설!!

In [46]:
import pandas as pd

xlsx = pd.read_excel('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/local_workation.xlsx')
xlsx.to_csv('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/local_workation.csv')

In [47]:
local_workation = pd.read_csv('/Users/imyeji/Desktop/공공데이터포럼_해커톤/데이터/accommodations/local_workation.csv')

In [48]:
local_workation

,Unnamed: 0,name,option,address,latitude,longitude
0,0,데스커 워케이션,워케이션 특화시설,강원 양양군 현남면 인구길 64,NaN,NaN
1,1,디어먼데이 통영,워케이션 특화시설,통영시 통영해안로 301,NaN,NaN
2,2,러스틱 타운,워케이션 특화시설,곡성군 오곡면 심청로 178,NaN,NaN
3,3,로컬스티치 대전,워케이션 특화시설,대전광역시 동구 계족로 209-1,NaN,NaN
4,4,질그랭이 거점센터,워케이션 특화시설,제주시 구좌읍 세평향로 46-9,NaN,NaN
5,5,청자강 복합문화공간,워케이션 특화시설,세종특별자치시 조치원읍 상리 120-7,NaN,NaN
6,6,코사이어티 빌리지,워케이션 특화시설,제주시 구좌읍 번영로 2133-50,NaN,NaN
7,7,O-Peace 제주(사계),워케이션 특화시설,서귀포시 향교로 214,NaN,NaN
8,8,O-Peace 제주(조천),워케이션 특화시설,제주시 조천2길 25,NaN,NaN
9,9,"강릉살자(파도살롱, 지역제퓨호텔)",스테이형 워케이션 시설,강릉시 경강로 2023,NaN,NaN
10,10,고요산책,스테이형 워케이션 시설,제주시 중앙로 12길 5,NaN,NaN
11,11,"괜찮아마을(카세트플레이어, 반짝반짝 1번지)",스테이형 워케이션 시설,목포시 노적봉길 21-1,NaN,NaN
12,12,"라이프밸리(소호259호스텔, 소호카페, 고구마쌀롱 등)",스테이형 워케이션 시설,속초시 수복로 259번길 11,NaN,NaN
13,13,"삶기술학교(커뮤니티호텔 H, 한산 디지털노마드센터)",스테이형 워케이션 시설,서천군 한산면 한산향교길 4,NaN,NaN
14,14,소랑이싯다,스테이형 워케이션 시설,제주시 신선길 8-2,NaN,NaN
15,15,아르카북스,스테이형 워케이션 시설,평택시 현덕면 덕목5길 122-11,NaN,NaN
16,16,"아웃도어 아일랜드(메이커스 캠프, 지역제휴호텔)",스테이형 워케이션 시설,거제시 장승포로 83-3,NaN,NaN
17,17,"자유도(버드나무빌, 슬로크루즈, 업스테어스, CREAM)",스테이형 워케이션 시설,공주시 감영길 9,NaN,NaN
18,18,골든튤립 호텔 남강,호텔&리조트형 워케이션 시설,진주시 남강로 673번길 16,NaN,NaN
19,19,그랜드 머큐리 호텔 창원,호텔&리조트형 워케이션 시설,창원시 성산구 원이대로 332,NaN,NaN
20,20,나인부띠끄 호텔,호텔&리조트형 워케이션 시설,서귀포시 솔동산롤 10번길 23,NaN,NaN
21,21,더 앤 리조트,호텔&리조트형 워케이션 시설,양양군 현남면 개매길 260,NaN,NaN
22,22,더 워크 앤 리조트,호텔&리조트형 워케이션 시설,인천광역시 중구 용유서로 379,NaN,NaN
23,23,더 제이드 호텔,호텔&리조트형 워케이션 시설,제주시 관덕로 15길 7-1,NaN,NaN
24,24,라까사호텔 광명,호텔&리조트형 워케이션 시설,광명시 일직로 12번길 22,NaN,NaN
25,25,라마다 군산 호텔,호텔&리조트형 워케이션 시설,군산시 대학로 400,NaN,NaN
26,26,롯데시티 호텔 울산,호텔&리조트형 워케이션 시설,울산광역시 남구 삼산로 204,NaN,NaN
27,27,롯데호텔 울산,호텔&리조트형 워케이션 시설,울산광역시 남구 삼산로 282,NaN,NaN
28,28,마레몬스 호텔,호텔&리조트형 워케이션 시설,속초시 동해대로 3705,NaN,NaN
29,29,시프트도어 레지던스,호텔&리조트형 워케이션 시설,부산광역시 영도구 동삼오션로 58,NaN,NaN
30,30,씨마크호텔,호텔&리조트형 워케이션 시설,강릉시 해안로 406번길 2 씨마크호텔,NaN,NaN
31,31,아비오 호텔,호텔&리조트형 워케이션 시설,강릉시 창해로 229,NaN,NaN
32,32,아이스퀘어 호텔,호텔&리조트형 워케이션 시설,김해시 김해대로 2360,NaN,NaN
33,33,오크우드 프리미어 인천,호텔&리조트형 워케이션 시설,인천광역시 연수구 컨벤시아대로 165,NaN,NaN
34,34,켄싱턴 리조트 지리산 하동점,호텔&리조트형 워케이션 시설,하동군 화개면 쌍계로 532-6,NaN,NaN
35,35,탑스텐 동강 시스타 리조트,호텔&리조트형 워케이션 시설,영월군 영월읍 사지막길 160,NaN,NaN
36,36,테이크 호텔,호텔&리조트형 워케이션 시설,광명시 신기로 22,NaN,NaN
37,37,토요코인 창원,호텔&리조트형 워케이션 시설,창원시 성산구 중앙대로 93,NaN,NaN
38,38,플레이스 캠프,호텔&리조트형 워케이션 시설,서귀포시 성산읍 동류암로 20,NaN,NaN
39,39,한화리조트 제주,호텔&리조트형 워케이션 시설,제주시 명림로 575-107,NaN,NaN
40,40,헤이 서귀포,호텔&리조트형 워케이션 시설,서귀포시 태평로 363 헤이 서귀포,NaN,NaN
41,41,가야산 생태탐방원,공공형 워케이션 시설,성주군 수륜면 봉양로 1길 313,NaN,NaN
42,42,내장산 생태탐방원,공공형 워케이션 시설,정읍시 내장호반로 266,NaN,NaN
43,43,한려해상 생태탑방원,공공형 워케이션 시설,통영시 산양읍 산양일주로 1361-96,NaN,NaN

In [52]:



# 데이터프레임 주소값 추출
address= local_workation['address']
print(address.head(10))

0        강원 양양군 현남면 인구길 64
1            통영시 통영해안로 301
2          곡성군 오곡면 심청로 178
3       대전광역시 동구 계족로 209-1
4        제주시 구좌읍 세평향로 46-9
5    세종특별자치시 조치원읍 상리 120-7
6      제주시 구좌읍 번영로 2133-50
7             서귀포시 향교로 214
8              제주시 조천2길 25
9            강릉시 경강로 2023
Name: address, dtype: object

In [53]:
!pip install geopy

####### 도로명주소 위도 경도 값으로 바꿔주기 ########
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

# 위도, 경도 반환하는 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

Collecting geopy
  Obtaining dependency information for geopy from https://files.pythonhosted.org/packages/e1/58/9289c6a03116025cdb61461d99b2493daa4967a80b13755463d71a0affeb/geopy-2.4.0-py3-none-any.whl.metadata
  Downloading geopy-2.4.0-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 2.9 MB/s eta 0:00:00
Downloading geopy-2.4.0-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.4/125.4 kB 10.3 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.0

In [54]:
#####주소를 위,경도 값으로 변환하기 #####
latitude = []
longitude =[]

for i in address:
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

In [55]:
print(geo_local)

<geopy.geocoders.nominatim.Nominatim object at 0x1310d2990>

In [56]:
#####Dataframe만들기######
geocoding_workation = pd.DataFrame({'name': local_workation['name'],'option':local_workation['option'],'address':address,'latitude':latitude,'longitude':longitude})

#df저장
geocoding_workation.to_csv('local_workation_geocoding.csv')